name: Auto Approve

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auto approve pull request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const pull_number = github.context.payload.pull_request.number;
            await octokit.pulls.createReview({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              pull_number,
              event: 'APPROVE'
            });